#! /bin/sh
#
# This script should be called by upssched via the CMDSCRIPT directive.
# 
# Here is a quick example to show how to handle a bunch of possible
# timer names with the help of the case structure.
#
# This script may be replaced with another program without harm.
#
# The first argument passed to your CMDSCRIPT is the name of the timer
# from your AT lines.

# shed
# shed-on
# poweroff-truenas
# poweron-truenas
# shutdown-proxmox

#case $1 in
#       onbattwarn)
#               # Send a notification mail
#               echo "The UPS has been on battery for awhile" \
#               | mail -s"UPS monitor" bofh@pager.example.com
#               # Create a flag-file on the filesystem, for your own processing
#               /usr/bin/touch /some/path/ups-on-battery
#               ;;
#       ups-back-on-power)
#               # Delete the flag-file on the filesystem
#               /bin/rm -f /some/path/ups-on-battery
#               ;;
#       upsgone)
#               logger -t upssched-cmd "The communication with UPS has been gone for awhile"
#               ;;
#       *)
#               logger -t upssched-cmd "Unrecognized command: $1"
#               ;;
#esac


# START: User-specific settings                            
# Use a user authorised to issue the commands below in upsd.users
UPS_USERNAME="upsmon"
UPS_PASSWORD="pass"
UPS_LINK="Eaton5Px@localhost"
# END  

case $1 in
    shed)
       message="Shedding group1"
       logger -t upssched-cmd "$message"
       upscmd -u ${UPS_USERNAME} -p ${UPS_PASSWORD} ${UPS_LINK} outlet.1.load.off
       ;;

    shed_on)
       message="Restoring group1"
       logger -t upssched-cmd "$message"
       upscmd -u ${UPS_USERNAME} -p ${UPS_PASSWORD} ${UPS_LINK} outlet.1.load.on
       ;;

    poweroff_truenas)
       message="Truenas power off"
       logger -t upssched-cmd "$message"
       upscmd -u ${UPS_USERNAME} -p ${UPS_PASSWORD} ${UPS_LINK} outlet.2.load.off
       ;;

    poweron_truenas)
       message="Truenas power off"
       logger -t upssched-cmd "$message"
       upscmd -u ${UPS_USERNAME} -p ${UPS_PASSWORD} ${UPS_LINK} outlet.2.load.on
       ;;

    shutdown_proxmox)
        message="shutting down self'
        logger -t upssched-cmd "$message"
        /bin/shutdown -h now
       ;;
    
    onpower)
        message="Power restored"
        logger -t upssched-cmd "$message"
        # wakeup NAS+backup in case they were shutdown and group1 was not shedded yet. (won't reboot as no power drop was detected)
        /usr/bin/WakeAll.sh
        ;;
   
     
    replace_batt)
        message="Quick self-test indicates battery requires replacement"
        logger -t upssched-cmd "$message"
        ;;
    

    *)
        logger -t upssched-cmd "Unrecognized command: $1"
        ;;
esac



